name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: github-hosted-small
    steps:
      - name: Check out repository code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          submodules: "recursive"

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.10"

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "18"

      - name: Install Solhint
        run: npm i

      - name: Run Linter
        run: npm run lint

      - name: Build Forge Image
        run: make build

      - name: Run Unit Tests
        run: make test
  
  build_success_rollup:
    runs-on: github-hosted-small
    name: Build Success Rollup
    if: ${{ always() }}
    needs:
      - lint-and-test
    steps:
      - run: |
          [ "${{ needs.lint-and-test.result }}" = "success" ] || [ "${{ needs.lint-and-test.result }}" = "skipped" ]

  scan:
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint-and-test
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1
